// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmrgoENimBvrBxKWsRI1SJgx4yU_vuP4c',
    appId: '1:687013298284:web:687d3bd5153726caaed849',
    messagingSenderId: '687013298284',
    projectId: 'delivery-93878',
    authDomain: 'delivery-93878.firebaseapp.com',
    storageBucket: 'delivery-93878.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgyw6mELhTxSVHUQlFZourKfFUmigSsrA',
    appId: '1:687013298284:android:7315d854e9f2b8fcaed849',
    messagingSenderId: '687013298284',
    projectId: 'delivery-93878',
    storageBucket: 'delivery-93878.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVtFY_q1pFJdEZe-YChXzXJ0OaL0959sk',
    appId: '1:687013298284:ios:7ebc1b8d304f3124aed849',
    messagingSenderId: '687013298284',
    projectId: 'delivery-93878',
    storageBucket: 'delivery-93878.firebasestorage.app',
    iosBundleId: 'com.gloomygold.delivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVtFY_q1pFJdEZe-YChXzXJ0OaL0959sk',
    appId: '1:687013298284:ios:7ebc1b8d304f3124aed849',
    messagingSenderId: '687013298284',
    projectId: 'delivery-93878',
    storageBucket: 'delivery-93878.firebasestorage.app',
    iosBundleId: 'com.gloomygold.delivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmrgoENimBvrBxKWsRI1SJgx4yU_vuP4c',
    appId: '1:687013298284:web:886fab577e728c64aed849',
    messagingSenderId: '687013298284',
    projectId: 'delivery-93878',
    authDomain: 'delivery-93878.firebaseapp.com',
    storageBucket: 'delivery-93878.firebasestorage.app',
  );
}